package bibletext

// Code generated by scripts/gen-omitted-verses.py. DO NOT EDIT BY HAND.
//
// The verses each translation OMITS: a number its own chapter skips,
// between verses it does print. Resolved offline from the publishers' own
// complete feeds, because the runtime cannot tell a hole from a merged
// verse or an interrupted fetch by looking at the numbering.
//
// Cross-checked against versification_data.go: every verse recorded there
// as absent from an edition appears here as a hole.
//
// Books whose numbering corresponds to nothing are excluded, so a gap in
// Greek Esther is not reported as an omission.

var omittedVerses = map[string]map[string]map[int][]int{
	"bsb": {
		"Acts":    {8: {37}, 15: {34}, 24: {7}, 28: {29}},
		"John":    {5: {4}},
		"Luke":    {17: {36}, 23: {17}},
		"Mark":    {7: {16}, 9: {44, 46}, 11: {26}, 15: {28}},
		"Matthew": {17: {21}, 18: {11}, 23: {14}},
		"Romans":  {16: {24}},
	},
	"web": {
		"Acts": {8: {37}, 15: {34}, 24: {7}},
		"Luke": {17: {36}},
	},
	"webc": {
		"Acts":   {8: {37}, 15: {34}, 24: {7}},
		"Luke":   {17: {36}},
		"Sirach": {1: {5, 7, 21}, 3: {19}, 10: {21}, 11: {15, 16}, 13: {14}, 16: {15, 16}, 17: {5, 9, 16, 18, 21}, 18: {3}, 19: {18, 19, 21}, 20: {3}, 22: {9, 10}, 24: {18, 24}, 25: {12}, 26: {19, 20, 21, 22, 23, 24, 25, 26, 27}},
	},
}
