package bibletext

import (
	"image/color"
	"strings"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
)

const bookRowHeight = 28

// buildSidebar creates the navigation panel once. Its widgets are persistent for
// the lifetime of the window: filtering and external navigation only refresh the
// book list, never rebuild the entry widgets, so typing never loses focus.
func buildSidebar(state *AppState) fyne.CanvasObject {
	pal := state.pal()

	// --- Search ---
	searchEntry := widget.NewEntry()
	searchEntry.SetPlaceHolder("Search…")
	searchEntry.SetText(state.SearchQuery)

	// Live search lists matches as you type, debounced so a fast typist doesn't
	// queue a whole-corpus scan + results rebuild on every keystroke; pressing
	// Enter cancels the pending run and additionally jumps to an exact verse ref.
	onSearchChanged, stopSearchDebounce := newSearchDebouncer(state)
	searchEntry.OnChanged = onSearchChanged
	searchEntry.OnSubmitted = func(s string) {
		stopSearchDebounce()
		executeSearch(state, s)
	}

	clearSearch := widget.NewButtonWithIcon("", theme.CancelIcon(), func() {
		searchEntry.SetText("")
	})
	clearSearch.Importance = widget.LowImportance
	searchRow := container.NewBorder(nil, nil, nil, clearSearch, inputFrame(withCaret(state, searchEntry), pal.Border))

	state.setSearchText = func(s string) {
		searchEntry.SetText(s)
	}

	// --- AI Find (natural-language passage search). Results replace the reading
	// pane (the same path as keyword search: IsSearching → buildReadingPane →
	// buildSearchResultsView), with the in-progress / no-key / error states driven from
	// state so the shared results view can render them. ---
	aiEntry := widget.NewEntry()
	aiEntry.SetPlaceHolder("In your own words…")
	aiEntry.SetText(state.aiSearchQuery)

	var runAsk func(string)
	runAsk = func(q string) {
		q = strings.TrimSpace(q)
		if q == "" {
			return
		}
		state.searchScrollY = 0
		state.aiSearchActive = true
		state.aiSearchQuery = q
		state.aiSearchErr = nil
		state.IsSearching = true // results replace the reading pane
		if !hasAIKey(state) {
			state.aiSearchResults = nil
			state.aiSearchLoading = false
			state.refresh() // → aiNoKeyView
			return
		}
		state.aiSearchResults = nil
		state.aiSearchLoading = true
		state.refresh() // → aiSearchingView
		startAISearch(state, q, func(verses []Verse, err error) {
			state.aiSearchLoading = false
			switch {
			case err != nil && isNoKeyError(err):
				state.aiSearchResults = nil
			case err != nil:
				state.aiSearchErr = err
				state.aiSearchResults = nil
			default:
				state.aiSearchResults = verses
			}
			state.refresh() // → results / error
		})
	}
	state.retryAISearch = func() { runAsk(state.aiSearchQuery) }
	aiEntry.OnSubmitted = runAsk

	clearAsk := widget.NewButtonWithIcon("", theme.CancelIcon(), func() {
		aiEntry.SetText("")
		state.aiSearchQuery = ""
		state.aiSearchResults = nil
		state.aiSearchErr = nil
		if state.IsSearching {
			state.refresh() // → prompt
		}
	})
	clearAsk.Importance = widget.LowImportance
	askBtn := widget.NewButtonWithIcon("", theme.SearchIcon(), func() { runAsk(aiEntry.Text) })
	askBtn.Importance = widget.LowImportance
	askRow := container.NewBorder(nil, nil, nil, container.NewHBox(clearAsk, askBtn), inputFrame(withCaret(state, aiEntry), pal.Border))

	// Field + caption swap with the Search/Find toggle.
	fieldHost := container.NewStack()
	captionHost := container.NewStack()
	keywordCaption := caption("Keyword, or a reference like John 3:16.")
	aiCaption := caption("These results are generated by AI and may be inaccurate or incomplete. Always read each passage in its full context and confirm it in Scripture.")
	applyMode := func() {
		if state.aiSearchMode {
			fieldHost.Objects = []fyne.CanvasObject{askRow}
			captionHost.Objects = []fyne.CanvasObject{aiCaption}
		} else {
			fieldHost.Objects = []fyne.CanvasObject{searchRow}
			captionHost.Objects = []fyne.CanvasObject{keywordCaption}
		}
		fieldHost.Refresh()
		captionHost.Refresh()
	}
	toggle := buildSearchModeToggle(state, func(ai bool) {
		state.aiSearchMode = ai
		state.aiSearchActive = ai
		applyMode()
		if state.IsSearching {
			state.refresh() // re-render the results in the new mode's context
		}
	})

	state.focusSearch = func() {
		if state.window == nil {
			return
		}
		if state.aiSearchMode {
			state.window.Canvas().Focus(aiEntry)
		} else {
			state.window.Canvas().Focus(searchEntry)
		}
	}

	// --- Book filter + list ---
	filtered := filterBooks(state.Bible.Books, state.BookFilterQuery)

	bookFilter := widget.NewEntry()
	bookFilter.SetPlaceHolder("Filter books")
	bookFilter.SetText(state.BookFilterQuery)

	list := widget.NewList(
		func() int { return len(filtered) },
		func() fyne.CanvasObject {
			label := canvas.NewText("", pal.Text)
			label.TextSize = 13
			return container.NewPadded(label)
		},
		func(i widget.ListItemID, obj fyne.CanvasObject) {
			if i < 0 || i >= len(filtered) {
				return
			}
			label := obj.(*fyne.Container).Objects[0].(*canvas.Text)
			book := filtered[i]
			label.Text = book
			if book == state.CurrentBook {
				label.Color = pal.Accent
				label.TextStyle = fyne.TextStyle{Bold: true}
			} else {
				label.Color = pal.Text
				label.TextStyle = fyne.TextStyle{}
			}
			label.Refresh()
		},
	)
	applyRowHeights(list, len(filtered))

	scrollToCurrent := func() {
		if id := indexOfBook(filtered, state.CurrentBook); id >= 0 {
			list.ScrollTo(widget.ListItemID(id))
		}
	}
	scrollToCurrent()

	list.OnSelected = func(id widget.ListItemID) {
		if id < 0 || id >= len(filtered) {
			return
		}
		selectBook(state, filtered[id], true)
		state.refresh()
	}

	bookFilter.OnChanged = func(s string) {
		state.BookFilterQuery = s
		filtered = filterBooks(state.Bible.Books, s)
		applyRowHeights(list, len(filtered))
		list.UnselectAll()
		list.Refresh()
		scrollToCurrent()
	}

	// syncSidebar re-highlights the current book without disturbing the entries.
	state.syncSidebar = func() {
		list.UnselectAll()
		list.Refresh()
		scrollToCurrent()
	}

	header := container.NewVBox(
		sectionLabel("READ", pal),
		toggle,
		fieldHost,
		captionHost,
		spacer(10),
		sectionLabel("BOOKS", pal),
		inputFrame(withCaret(state, bookFilter), pal.Border),
	)
	applyMode() // initialise the field + caption to the persisted mode

	body := container.NewBorder(header, nil, nil, nil, list)
	return surface(body, pal.SurfaceAlt, pal.Border, fyne.NewSize(210, 0))
}

func applyRowHeights(list *widget.List, n int) {
	for i := 0; i < n; i++ {
		list.SetItemHeight(widget.ListItemID(i), bookRowHeight)
	}
}

func sectionLabel(text string, pal palette) fyne.CanvasObject {
	t := canvas.NewText(text, pal.TextMuted)
	t.TextSize = 11
	t.TextStyle = fyne.TextStyle{Bold: true, Monospace: true}
	return t
}

// caption is a small, muted hint that wraps to the sidebar width so it never
// clips, regardless of how narrow the panel is.
func caption(text string) fyne.CanvasObject {
	rt := widget.NewRichText(&widget.TextSegment{
		Text:  text,
		Style: widget.RichTextStyle{SizeName: theme.SizeNameCaptionText, ColorName: colorNameMuted},
	})
	rt.Wrapping = fyne.TextWrapWord
	return rt
}

func spacer(h float32) fyne.CanvasObject {
	r := canvas.NewRectangle(color.Transparent)
	r.SetMinSize(fyne.NewSize(0, h))
	return r
}

func hgap(w float32) fyne.CanvasObject {
	r := canvas.NewRectangle(color.Transparent)
	r.SetMinSize(fyne.NewSize(w, 0))
	return r
}
