Website = "https://bibletext.co.uk"

[Details]
Icon = "Icon.png"
Name = "BibleText"
ID = "uk.co.bibletext"
Version = "1.2.11"
Build = 52

[CanOpen]
MimeTypes = "x-scheme-handler/bibletext;"

[LinuxAndBSD]
GenericName = "Bible reader"
Comment = "Read and study Scripture"
Categories = ["Education", "Spirituality"]
Keywords = ["Bible", "Scripture", "NKJV", "Berean", "WEB", "BSB", "Catholic", "deuterocanon", "audio", "narration", "notes", "offline"]
