#!/usr/bin/env bash
# Compile the project's own API.Bible key into a RELEASE build.
#
# Sourced (not run) by the packaging scripts:
#
#     source "$REPO_ROOT/scripts/embed-bible-key.sh"
#     embed_bible_key            # writes the generated file, arms the cleanup
#
# It generates bundled_key_gen.go — gitignored, obfuscated, and removed by an
# EXIT trap so the key never survives the build, never reaches the repo, and
# never appears in a developer build. The same temporary-file discipline the
# patched-Fyne step uses.
#
# The key comes from BIBLE_API_KEY (exported, or the repo's .env.local). With
# no key present the build simply proceeds WITHOUT one: that is the kill
# switch — new installs are bring-your-own-key again.
#
# Quota reality check (API.Bible free Starter): 5,000 calls/month for the whole
# account, ~197 for one NKJV download, and every device revalidates every 30
# days. That is roughly 25 active devices before a month runs dry, and when it
# does, every reader on the bundled key fails until the reset. Ship without the
# key once real usage approaches that.

BIBLE_KEY_GEN_FILE=""

# The cleanup trap is armed HERE, at source time, and not inside the function:
# in zsh a trap set inside a function fires when the FUNCTION returns, which
# would delete the generated file before the compiler ever sees it. Single
# quotes keep the path unexpanded until the trap actually runs.
trap 'rm -f "$BIBLE_KEY_GEN_FILE"' EXIT

embed_bible_key() {
  local root="${REPO_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
  local key="${BIBLE_API_KEY:-}"

  if [ -z "$key" ] && [ -f "$root/.env.local" ]; then
    key="$(grep -E '^BIBLE_API_KEY=' "$root/.env.local" | head -1 | cut -d= -f2- | tr -d '"'"'"' \r')"
  fi

  if [ -z "$key" ]; then
    echo "==> no BIBLE_API_KEY found — building WITHOUT a bundled key (readers supply their own)"
    return 0
  fi

  BIBLE_KEY_GEN_FILE="$root/bundled_key_gen.go"
  python3 - "$key" "$BIBLE_KEY_GEN_FILE" <<'PY'
import base64, json, sys
key, out = sys.argv[1], sys.argv[2]
mask = b"bibletext-nkjv"                       # must match bundledKeyMask
raw = key.encode()
enc = bytes(b ^ mask[i % len(mask)] for i, b in enumerate(raw))
# base64 is plain ASCII, so a JSON string literal is also a valid Go one.
literal = json.dumps(base64.b64encode(enc).decode())
with open(out, "w") as f:
    f.write("// Code generated by scripts/embed-bible-key.sh. DO NOT EDIT.\n")
    f.write("// Generated for one build and deleted afterwards; never committed.\n\n")
    f.write("package bibletext\n\n")
    f.write("func init() { bundledBibleKeyEnc = " + literal + " }\n")
PY
  if [ ! -s "$BIBLE_KEY_GEN_FILE" ]; then
    echo "!! failed to generate $BIBLE_KEY_GEN_FILE — aborting rather than shipping a keyless build silently" >&2
    rm -f "$BIBLE_KEY_GEN_FILE"
    return 1
  fi
  echo "==> bundled API.Bible key embedded for this build (…${key: -4}); shared quota ≈25 devices/month"
}
