#!/usr/bin/env python3
"""Build the NKJV's red-letter spans from the publisher's own markup.

    BIBLETEXT_PROVIDER_ID_NKJV=<provider-id> \
        python3 scripts/gen-nkjv-redletter.py      # fetch (cached), then derive

The NKJV's own spans are served by API.Bible as <span class="wj">. This is the publisher's editorial
judgement, not ours, which is the right basis for a licensed edition.

QUOTA. Each chapter is one API call and the account's allowance is small, so
every raw response is written to ~/.cache/bibletext-nkjv-html and NEVER
re-fetched: a run with a warm cache makes zero calls. The nine books with any
red letters are 174 chapters, i.e. 174 calls once, ever. Do not point this at a
cold cache casually.

LICENSING. The cache lives outside the repository and the generated Go file
holds OFFSETS ONLY — no NKJV text is stored anywhere in this repo. An offset is
a fact about the text rather than the text itself.

The offsets are located by matching each marked span's TEXT inside the app's own
verse text, tolerating whitespace differences: API.Bible's HTML runs verses
together without the space the app's copy has, so raw offsets from the HTML do
not transfer. All 2,054 marked verses located cleanly at the time of writing.
"""
import json
import os
import subprocess
import sys
import time
import urllib.error
import urllib.parse
import urllib.request

CACHE=os.path.expanduser('~/.cache/bibletext-nkjv-html')
KEY=os.environ.pop('BIBLE_API_KEY', '').strip()
PID=os.environ.pop('BIBLETEXT_PROVIDER_ID_NKJV', '').strip()
for personal_key_var in ('ANTHROPIC_API_KEY', 'OPENAI_API_KEY', 'GEMINI_API_KEY', 'XAI_API_KEY'):
    os.environ.pop(personal_key_var, None)

# This generator never opens the repository's general-purpose .env.local,
# which may contain unrelated personal provider credentials. On macOS it may
# use the same dedicated API.Bible Keychain item as the release pipeline.
if not KEY and sys.platform == 'darwin':
    result = subprocess.run(
        ['security', 'find-generic-password', '-a', 'release',
         '-s', 'uk.co.bibletext.apibible-release', '-w'],
        check=False, capture_output=True, text=True,
    )
    if result.returncode == 0:
        KEY = result.stdout.strip()
    result.stdout = ''
    result.stderr = ''
    del result

if not KEY or not PID:
    missing = []
    if not KEY:
        missing.append('BIBLE_API_KEY (or the dedicated macOS Keychain item)')
    if not PID:
        missing.append('BIBLETEXT_PROVIDER_ID_NKJV')
    raise SystemExit('Missing ' + ' and '.join(missing))
BOOKS={'Matthew':('MAT',28),'Mark':('MRK',16),'Luke':('LUK',24),'John':('JHN',21),'Acts':('ACT',28),
       '1 Corinthians':('1CO',16),'2 Corinthians':('2CO',13),'1 Timothy':('1TI',6),'Revelation':('REV',22)}
calls=0


class SameOriginRedirectHandler(urllib.request.HTTPRedirectHandler):
    def redirect_request(self, req, fp, code, msg, headers, newurl):
        old = urllib.parse.urlsplit(req.full_url)
        new = urllib.parse.urlsplit(newurl)
        if (old.scheme.lower(), old.netloc.lower()) != (new.scheme.lower(), new.netloc.lower()):
            raise urllib.error.HTTPError(
                newurl, code, 'cross-origin redirect refused', headers, fp)
        return super().redirect_request(req, fp, code, msg, headers, newurl)


OPENER = urllib.request.build_opener(SameOriginRedirectHandler())
for book,(code,n) in BOOKS.items():
    for ch in range(1,n+1):
        path=os.path.join(CACHE,f"{code}.{ch}.json")
        if os.path.exists(path) and os.path.getsize(path)>200: continue   # never re-fetch
        url=(f"https://api.scripture.api.bible/v1/bibles/{PID}/chapters/{code}.{ch}"
             "?content-type=html&include-notes=false&include-verse-spans=true")
        try:
            with OPENER.open(urllib.request.Request(url,headers={'api-key':KEY}),timeout=45) as r:
                raw=r.read()
            open(path,'wb').write(raw); calls+=1
        except Exception as e:
            print(f"  {code}.{ch}: {type(e).__name__} {e}",file=sys.stderr)
            time.sleep(2)
print(f"API calls made this run: {calls}; cached chapters: {len(os.listdir(CACHE))}",file=sys.stderr)
KEY = None

# ---------------------------------------------------------------- derive
# THE HALF THAT WAS MISSING. Until 20 Aug 2026 this script ended at the fetch,
# while red_letter_nkjv_data.go claimed to be generated by it — the extraction
# that actually produced the table was never committed, and it carried a bug
# this rewrite exists to fix: the NKJV italicises supplied words, API.Bible
# nests those as <span class="it"> INSIDE <span class="wj">, and the lost
# extractor stopped at the first nested element. Every quotation containing an
# italicised word was truncated at that word: Matthew 11:30 kept "For My yoke"
# of "For My yoke *is* easy and My burden is light."; Matthew 27:11 kept one
# rune of a 144-rune verse. Measured against the shipped table: 411 of 2,054
# verses had red covering under half the verse.
#
# THE RULE, stated once: every character of TEXT that lies inside a <span
# class="wj"> belongs to Christ's words, whatever elements it is nested in —
# except a verse NUMBER (class "v"), which is display chrome the app's verse
# text does not contain. Contiguity in document order defines a span; a change
# of verse or a new wj block starts a new one.

from html.parser import HTMLParser

class WJExtract(HTMLParser):
    """Per verse, the contiguous red runs, as text fragments in document order."""
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.stack = []          # class-list per open span, innermost last
        self.verse = None        # current verse id, e.g. "MAT.11.30"
        self.runs = {}           # verse id -> [ [fragments...], ... ]
        self._open = {}          # verse id -> True while its current run continues

    def handle_starttag(self, tag, attrs):
        if tag != "span":
            self.stack.append(set()); return
        a = dict(attrs)
        cls = set((a.get("class") or "").split())
        self.stack.append(cls)
        if "verse-span" in cls and a.get("data-verse-id"):
            self.verse = a["data-verse-id"]

    def handle_endtag(self, tag):
        if self.stack:
            cls = self.stack.pop()
            # closing a wj ends every verse's current run: red text after this
            # (a later wj) is a NEW quotation, not a continuation.
            if "wj" in cls:
                self._open.clear()

    def handle_data(self, data):
        in_wj = any("wj" in c for c in self.stack)
        in_num = any("v" in c for c in self.stack)
        in_head = any("s" in c for c in self.stack)
        if not in_wj or in_num or in_head or self.verse is None:
            return
        if not data.strip():
            # bare whitespace joins an open run but never opens one
            if self._open.get(self.verse):
                self.runs[self.verse][-1].append(data)
            return
        if not self._open.get(self.verse):
            self.runs.setdefault(self.verse, []).append([])
            # a new run for THIS verse closes every other verse's run: the
            # quotation moved on, and fragments of another verse can no longer
            # be contiguous with their old run.
            self._open = {self.verse: True}
        self.runs[self.verse][-1].append(data)

def rune_map(s):
    """chars-with-whitespace-stripped, casefolded -> rune index in the original.

    Case-insensitive because the app's decoder renders the NKJV's small-caps
    divine name as "LORD" while the HTML carries "Lord" inside <span class="sc">
    — same characters, different case, and it cost 14 verses on the first run.
    Lowercasing is done per character so lengths cannot drift and every stripped
    character keeps its original rune index.
    """
    stripped, idx = [], []
    for i, ch in enumerate(s):
        if not ch.isspace():
            stripped.append(ch.lower()); idx.append(i)
    return "".join(stripped), idx

def locate(run_text, verse_text, cursor_nospace):
    """Find run_text in verse_text ignoring ALL whitespace differences.
    Returns (start_rune, end_rune, new_cursor) or None."""
    needle = "".join(ch.lower() for ch in run_text if not ch.isspace())
    if not needle:
        return None
    hay, idx = rune_map(verse_text)
    at = hay.find(needle, cursor_nospace)
    if at < 0 and cursor_nospace:            # same phrase twice: retry from 0
        at = hay.find(needle)
    if at < 0:
        return None
    return idx[at], idx[at + len(needle) - 1] + 1, at + len(needle)

def fnv1a64(text):
    value = 0xCBF29CE484222325
    for byte in text.encode('utf-8'):
        value ^= byte
        value = (value * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
    return value

def derive():
    import glob
    app_cache = None
    for pat in (
        os.path.expanduser("~/Library/Caches/bibletext/bibletext-nkjv.json"),
        os.path.expanduser("~/Library/Developer/CoreSimulator/Devices/*/data/Containers/Data/Application/*/Library/Caches/bibletext/bibletext-nkjv.json"),
    ):
        hits = sorted(glob.glob(pat), key=os.path.getmtime, reverse=True)
        if hits:
            app_cache = hits[0]; break
    if not app_cache:
        sys.exit("no bibletext-nkjv.json found — open the NKJV in the app or a simulator once")
    print(f"app text: {app_cache}", file=sys.stderr)

    data = json.load(open(app_cache))["data"]["Verses"]
    def app_text(book, ch, v):
        for rec in data.get(book, {}).get(str(ch), []):
            if rec["Verse"] == v:
                return rec["Text"]
        return None

    code_to_book = {code: book for book, (code, _) in BOOKS.items()}
    spans, lengths, hashes, failed = {}, {}, {}, []
    for book, (code, n) in BOOKS.items():
        for ch in range(1, n + 1):
            path = os.path.join(CACHE, f"{code}.{ch}.json")
            if not os.path.exists(path):
                continue
            html = json.load(open(path))["data"]["content"]
            p = WJExtract(); p.feed(html)
            for vid, runs in p.runs.items():
                vcode, vch, vv = vid.split(".")
                vbook = code_to_book[vcode]
                text = app_text(vbook, int(vch), int(vv))
                key = f"{vbook} {int(vch)}:{int(vv)}"
                if text is None:
                    failed.append((key, "no app text")); continue
                cursor, out = 0, []
                for frags in runs:
                    got = locate("".join(frags), text, cursor)
                    if got is None:
                        failed.append((key, repr("".join(frags))[:60])); out = None; break
                    a, b, cursor = got
                    # merge with the previous span when touching/overlapping
                    if out and a <= out[-1][1]:
                        out[-1] = (out[-1][0], max(out[-1][1], b))
                    else:
                        out.append((a, b))
                if out:
                    spans[key] = out
                    lengths[key] = len(text)
                    hashes[key] = fnv1a64(text)

    if failed:
        print(f"FAILED to locate {len(failed)} runs:", file=sys.stderr)
        for k, why in failed[:20]:
            print(f"  {k}: {why}", file=sys.stderr)
        sys.exit(1)

    out_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "red_letter_nkjv_data.go")
    with open(out_path, "w") as f:
        f.write("""package bibletext

// Code generated by scripts/gen-nkjv-redletter.py. DO NOT EDIT BY HAND.
//
// Which words of each NKJV verse are Christ's, as rune offsets into the verse
// text. These are the NKJV's OWN words-of-Jesus spans, served by
// API.Bible as <span class="wj"> and located inside the app's verse text.
//
// OFFSETS ONLY. The NKJV is licensed (© 1982 Thomas Nelson) and none of its text
// is stored here or anywhere else in this repository; an offset is a fact about
// the text, not the text.
//
// REGENERATED 2026-08-20: the first table was cut by a lost extractor that
// stopped at the NKJV's italicised supplied words (<span class="it"> nested
// inside the wj markup) — 411 of 2,054 verses had most of their red missing,
// visibly on Matthew 11:28-30. Text inside a wj now counts wherever it is
// nested; only verse-number chrome is excluded.

var nkjvRedLetterSpans = map[string][]redLetterSpan{
""")
        for key in sorted(spans):
            body = ", ".join("{%d, %d}" % s for s in spans[key])
            f.write('\t"%s": {%s},\n' % (key, body))
        f.write("}\n\n// nkjvRedLetterRunes is the rune length of each verse the spans were computed\n// against. It is checked together with the content fingerprint below.\nvar nkjvRedLetterRunes = map[string]int{\n")
        for key in sorted(lengths):
            f.write('\t"%s": %d,\n' % (key, lengths[key]))
        f.write("}\n\n// nkjvRedLetterHashes binds the offsets to the exact runtime text revision.\nvar nkjvRedLetterHashes = map[string]uint64{\n")
        for key in sorted(hashes):
            f.write('\t"%s": 0x%016x,\n' % (key, hashes[key]))
        f.write("}\n")
    subprocess.run(["gofmt", "-w", out_path], check=True)
    print(f"wrote {out_path}: {len(spans)} verses", file=sys.stderr)

derive()
