#!/usr/bin/env bash
#
# setup-fyne-patch.sh — regenerate the patched copy of Fyne that this project
# builds against.
#
# WHY THIS EXISTS
#   The iOS scroll-lag fix is a one-line change *inside Fyne* (its mobile render
#   loop), not in our own code — so it cannot live in a normal source file. We
#   apply it by pointing the build at a local copy of Fyne via the go.mod line:
#       replace fyne.io/fyne/v2 => ./third_party/fyne
#   To avoid committing a ~22 MB fork, third_party/fyne is .gitignored and
#   REGENERATED by this script from the stock module cache + a tiny tracked patch
#   (patches/fyne-2.7.4-ios-drawloop.patch). See patches/README.md for the full
#   story and for how to remove the patch entirely.
#
# USAGE
#   ./scripts/setup-fyne-patch.sh
#   Run this once after cloning (and after any `go clean -modcache`) BEFORE
#   building for iOS. Safe to re-run; it rebuilds third_party/fyne from scratch.
#
set -euo pipefail
cd "$(dirname "$0")/.."   # repo root

FYNE_VERSION="v2.7.4"                                  # MUST match the require in go.mod
PATCH="patches/fyne-2.7.4-ios-drawloop.patch"
DEST="third_party/fyne"

# Guard: the patch is tied to this exact Fyne version. If go.mod's require has
# moved, the patch may not apply — regenerate it (see patches/README.md).
if ! grep -q "fyne.io/fyne/v2 ${FYNE_VERSION}" go.mod; then
  echo "WARNING: go.mod does not require fyne.io/fyne/v2 ${FYNE_VERSION}." >&2
  echo "         This patch was generated against ${FYNE_VERSION}; verify before continuing." >&2
fi

# 1. Make sure STOCK fyne is in the module cache. We fetch it from a throwaway
#    temp module so our own `replace` directive (which points back here) can't
#    redirect the download.
CACHE="$(go env GOMODCACHE)/fyne.io/fyne/v2@${FYNE_VERSION}"
if [ ! -d "$CACHE" ]; then
  echo "Stock fyne ${FYNE_VERSION} not in cache; fetching..."
  TMP="$(mktemp -d)"
  ( cd "$TMP" && go mod init _fyne_fetch >/dev/null 2>&1 \
      && go mod download "fyne.io/fyne/v2@${FYNE_VERSION}" )
  rm -rf "$TMP"
fi
[ -d "$CACHE" ] || { echo "ERROR: cannot locate stock fyne ${FYNE_VERSION} at $CACHE" >&2; exit 1; }

# 2. Copy it in (writable) and apply the one-line patch.
echo "Regenerating ${DEST} from ${CACHE} ..."
rm -rf "$DEST"
mkdir -p third_party
cp -R "$CACHE" "$DEST"
chmod -R u+w "$DEST"
patch -p1 -d "$DEST" < "$PATCH"

# 3. Verify the patch actually landed.
TARGET="$DEST/internal/driver/mobile/app/darwin_ios.go"
if grep -q "BibleText patch: was 100ms" "$TARGET"; then
  echo "OK: ${DEST} regenerated and patched (fyne ${FYNE_VERSION}, drawloop 100ms -> 2ms)."
else
  echo "ERROR: patch did not apply — '$TARGET' is unpatched." >&2
  exit 1
fi
